accounts/urls.py
from accounts.views import AccountLoginView
from accounts.views import AccountLogoutView
from accounts.views import AccountRegisterView
from accounts.views import AccountUpdateProfileView
from accounts.views import account_profile_view
from accounts.views import user_activate

from django.urls import path
from django.views.generic import TemplateView

app_name = 'accounts'

urlpatterns = [
    path('registration/activate/<str:sign>/', user_activate, name='register_activate'),
    path('registration/done/', TemplateView.as_view(template_name='accounts/register_done.html'), name='register_done'),
    path('registration/', AccountRegisterView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', account_profile_view, name='profile'),
    path('profile_change/', AccountUpdateProfileView.as_view(), name='profile_change'),
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('quiz.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser, Group
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True)
    avatar = models.ImageField(upload_to='profile/', default='profile/default.png')
    birthday = models.DateField(null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)

    class Meta(AbstractUser.Meta):
        permissions = [
            ('view_statistics', 'Can view statistics'),
        ]

    def __str__(self):
        return self.username


@receiver(post_save, sender=CustomUser)
def move_user_to_group(sender, instance, created, **kwargs):
    if created:
        instance.groups.add(Group.objects.get(name='Users'))

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserChangeForm
from django.core.exceptions import ValidationError

from .apps import user_registered


class AccountRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(
        label='Password:',
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html
    )
    password2 = forms.CharField(
        label='Confirm password:',
        widget=forms.PasswordInput,
        help_text='Please repeat password'
    )

    def clean_password1(self):
        pwd = self.cleaned_data['password1']
        if pwd:
            password_validation.validate_password(pwd)

        return pwd

    def clean(self):
        super().clean()
        pwd1 = self.cleaned_data.get('password1')
        pwd2 = self.cleaned_data.get('password2')
        if pwd1 and pwd2 and pwd1 != pwd2:
            raise ValidationError(
                {
                    'password2': ValidationError('Password not equals', code='password_mismatch')
                }
            )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_activated = False
        user.is_active = False

        if commit:
            user.save()

        user_registered.send(AccountRegisterForm, instance=user)

        return user

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )


class AccountUpdateForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'birthday',
            'city',
            'avatar',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'})
        }

accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.core.signing import BadSignature
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import UpdateView
# from django.views.generic import TemplateView

from .forms import AccountRegisterForm
from .forms import AccountUpdateForm
from .utils import signer


class AccountRegisterView(CreateView):
    model = get_user_model()
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:register_done')
    form_class = AccountRegisterForm


# class AccountRegisterDoneView(TemplateView):
#     template_name = 'accounts/register_done.html'


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, 'accounts/bad_signature.html')

    user = get_object_or_404(get_user_model(), username=username)
    if user.is_activated:
        template = 'accounts/user_is_activated.html'
    else:
        template = 'accounts/activation_done.html'
        user.is_activated = True
        user.is_active = True
        user.save()

    return render(request, template)


class AccountLoginView(LoginView):
    template_name = 'accounts/login.html'

    def get_redirect_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url

        return reverse('index')


class AccountLogoutView(LogoutView):
    template_name = 'accounts/logout.html'


def account_profile_view(request):
    return render(request, 'accounts/profile.html')


class AccountUpdateProfileView(UpdateView):
    template_name = 'accounts/profile_update.html'
    model = get_user_model()
    success_url = reverse_lazy('accounts:profile')
    form_class = AccountUpdateForm

    def get_object(self, queryset=None):
        return self.request.user

accounts/templates/accounts/activation_done.html
{% extends 'base.html' %}

{% block title %}
    Активация выполнена
{% endblock %}

{% block header %}
    Активация выполнена.
{% endblock %}

{% block content %}
    <p>Пользователь успешно активирован.</p>
    <p><a href="{% url 'accounts:login' %}">Войти на сайт.</a></p>
{% endblock %}

accounts/templates/accounts/bad_signature.html
{% extends 'base.html' %}

{% block title %}
    Активация не успешна
{% endblock %}

{% block header %}
    Активация не успешна.
{% endblock %}

{% block content %}
    <p>Активация прошла неудачно.</p>
    <p><a href="{% url 'accounts:register' %}">Зарегистрироваться повторно.</a></p>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
    Вход на сайт
{% endblock %}

{% block header %}
    Вход на сайт
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <p>
            Если Вы забыли свой пароль, мы можем Вам помочь. Перейдите по
            <a href="{% url 'password_reset' %}">ссылке</a> для сброса пароля.
        </p>
        <div>
            <input class="btn btn-success mt-3" type="submit" value="Логин">
            <a class="btn btn-success mt-3" href="{% url 'accounts:registration' %}">Регистрация</a>
        </div>
    </form>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block title %}
    Выход
{% endblock %}

{% block header %}
    Вы успешно вышли с сайта.
{% endblock %}

{% block content %}
    <a class="btn btn-success mt-3" href="{% url 'accounts:login' %}">Вход на сайт</a>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Профиль пользователя
{% endblock %}

{% block header %}
    {{ user.username }} профиль.
{% endblock %}

{% block content %}
    <div class="row mb-3">
      <div class="col-sm-10">
          <img class="rounded-circle p-1 m-1" width="200" height="200" src="{{ user.avatar.url }}" alt="avatar">
      </div>
    </div>
    <div class="row mb-3">
      <label for="username" class="col-sm-2"><strong>Username:</strong></label>
      <div class="col-sm-10">
          <p id="username">{{ user.username }}</p>
      </div>
    </div>
    <div class="row mb-3">
      <label for="firstname" class="col-sm-2"><strong>Имя:</strong></label>
      <div class="col-sm-10">
          <p id="firstname">{{ user.first_name }}</p>
      </div>
    </div>
    <div class="row mb-3">
      <label for="lastname" class="col-sm-2"><strong>Фамилия:</strong></label>
      <div class="col-sm-10">
          <p id="lastname">{{ user.last_name }}</p>
      </div>
    </div>
    <div class="row mb-3">
      <label for="email" class="col-sm-2"><strong>E-Mail:</strong></label>
      <div class="col-sm-10">
          <p id="email">{{ user.email }}</p>
      </div>
    </div>
    <div class="row mb-3">
      <label for="birthday" class="col-sm-2"><strong>Дата рождения:</strong></label>
      <div class="col-sm-10">
          <p id="birthday">{{ user.birthday }}</p>
      </div>
    </div>
    <div class="row mb-3">
      <label for="city" class="col-sm-2"><strong>Город:</strong></label>
      <div class="col-sm-10">
          <p id="city">{{ user.city }}</p>
      </div>
    </div>
    <a class="btn btn-primary" href="{% url 'accounts:profile_change' %}">Изменить профиль</a>
{% endblock %}

accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
    Обновление профиля
{% endblock %}

{% block header %}
    Обновление профиля
{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="media">
            <div class="img-circle.vert">
                <img class="rounded-circle p-1 m-1" width="200" height="200" src="{{ user.avatar.url }}" alt="avatar">
            </div>
            <div class="media-body p-3 m-3">
                <h2 class="account-heading">{{ user.username }}</h2>
                <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                {{ form.username|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.email|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.first_name|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.last_name|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.birthday|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.city|as_crispy_field }}
            </div>
        </div>
        {{ form.avatar|as_crispy_field }}

        <input class="btn btn-success mt-3" type="submit" value="Сохранить">
        <a class="btn btn-success mt-3" href="{% url 'accounts:profile' %}">Отменить</a>
    </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
    Регистрация нового пользователя
{% endblock %}

{% block header %}
    Регистрация нового пользователя.
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}

        <input class="btn btn-success mt-3" type="submit" value="Регистрация">
        <a class="btn btn-success mt-3" href="{% url 'accounts:login' %}">Вход</a>
    </form>
{% endblock %}

accounts/templates/accounts/register_done.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Регистрация завершена
{% endblock %}

{% block header %}
    Регистрация завершена.
{% endblock %}

{% block content %}
    <p>Регистрация пользователя завершена.</p>
    <p>На Ваш электронный адрес выслано письмо для активации учётной записи.</p>
{% endblock %}

accounts/templates/accounts/user_is_activated.html
{% extends 'base.html' %}

{% block title %}
    Пользователь уже активирован
{% endblock %}

{% block header %}
    Пользователь уже активирован.
{% endblock %}

{% block content %}
    <p>Пользователь с таким именем был активирован ранее.</p>
    <p><a href="{% url 'accounts:login' %}">Войти на сайт.</a></p>
{% endblock %}