accounts/urls.py
from accounts.views import AccountLoginView
from accounts.views import AccountLogoutView
from accounts.views import AccountRegisterView
from accounts.views import AccountUpdateProfileView
from accounts.views import account_profile_view
from accounts.views import user_activate

from django.urls import path
from django.views.generic import TemplateView

app_name = 'accounts'

urlpatterns = [
    path('registration/activate/<str:sign>/', user_activate, name='register_activate'),
    path('registration/done/', TemplateView.as_view(template_name='accounts/register_done.html'), name='register_done'),
    path('registration/', AccountRegisterView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', account_profile_view, name='profile'),
    path('profile_change/', AccountUpdateProfileView.as_view(), name='profile_change'),
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('quiz.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from django.urls import path

from quiz.views import ExamDetailView
from quiz.views import ExamListView
from quiz.views import ExamResultCreateView
from quiz.views import ExamResultDeleteView
from quiz.views import ExamResultDetailView
from quiz.views import ExamResultQuestionView
from quiz.views import ExamResultUpdateView

app_name = 'quiz'

urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('<uuid:uuid>/', ExamDetailView.as_view(), name='details'),
    path('<uuid:uuid>/result/create/', ExamResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/details/', ExamResultDetailView.as_view(), name='result_details'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/update/', ExamResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/delete/', ExamResultDeleteView.as_view(), name='result_delete'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/question/next/', ExamResultQuestionView.as_view(), name='question'),
]

templates/includes/nav_bar.html
{% load static %}

<nav class="navbar navbar-light fixed-top navbar-expand-lg font-weight-bold" style="background-color: #e3f2fd;">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">QUIZ</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'quiz:list' %}">Exam list</a>
          </li>
<!--        <li class="nav-item"><a class="nav-link" href="/contacts/">Contacts</a></li>-->
<!--        <li class="nav-item"><a class="nav-link" href="/about/">About Us</a></li>-->
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown3" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {% if user.is_authenticated %}
              <img class="rounded-circle" width="30" height="30" src="{{ user.avatar.url }}" alt="avatar">
              {{ user.username }}
            {% else %}
              <img class="rounded-circle" width="30" height="30" src="{% static 'accounts/default.png' %}" alt="avatar">
              Account
            {% endif %}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown3">
          {% if user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile {{ user.username }}</a></li>
            <li><a class="dropdown-item" href="{% url 'password_change' %}">Change password</a></li>
          {% else %}
            <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'accounts:registration' %}">Register</a></li>
          {% endif %}
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
<nav aria-label="paginator">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1"><i class="bi bi-chevron-double-left"></i></a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="bi bi-chevron-left"></i></a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-double-left"></i></a></li>
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-left"></i></a></li>
        {% endif %}

        {% for page_num in page_obj.paginator.page_range %}
            {% if page_num == page_obj.number %}
                <li class="page-item active"><a class="page-link">{{ page_num }}</a></li>
            {% elif page_num > page_obj.number|add:-3 and page_num < page_obj.number|add:3 %}
                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="bi bi-chevron-right"></i></a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"><i class="bi bi-chevron-double-right"></i></a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-right"></i></a></li>
        <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-double-right"></i></a></li>
        {% endif %}
    </ul>
</nav>