app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('quiz/', include('quiz.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quiz/urls.py
from django.urls import path

from quiz.views import ExamDetailView
from quiz.views import ExamListView
from quiz.views import ExamResultCreateView
from quiz.views import ExamResultDeleteView
from quiz.views import ExamResultDetailView
from quiz.views import ExamResultQuestionView
from quiz.views import ExamResultUpdateView

app_name = 'quiz'

urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('<uuid:uuid>/', ExamDetailView.as_view(), name='details'),
    path('<uuid:uuid>/result/create/', ExamResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/details/', ExamResultDetailView.as_view(), name='result_details'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/update/', ExamResultUpdateView.as_view(), name='result_update'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/delete/', ExamResultDeleteView.as_view(), name='result_delete'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/question/next/', ExamResultQuestionView.as_view(), name='question'),
]

quiz/models.py
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.db import models


class BaseModel(models.Model):
    create_timestamp = models.DateTimeField(auto_now_add=True)
    update_timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Exam(BaseModel):
    QUESTION_MIN_LIMIT = 3
    QUESTION_MAX_LIMIT = 100

    class LEVEL(models.IntegerChoices):
        BASIC = 0, 'Basic'
        MIDDLE = 1, 'Middle'
        ADVANCED = 2, 'Advanced'

    uuid = models.UUIDField(default=uuid4, db_index=True, unique=True)
    title = models.CharField(max_length=64)
    description = models.TextField(null=True, blank=True)
    level = models.PositiveSmallIntegerField(choices=LEVEL.choices, default=LEVEL.BASIC)

    def __str__(self):
        return self.title

    def questions_count(self):
        return self.questions.count()

    class Meta:
        verbose_name = 'Exam'
        verbose_name_plural = 'Exams'


class Question(BaseModel):
    exam = models.ForeignKey(Exam, related_name='questions', on_delete=models.CASCADE)
    order_num = models.PositiveSmallIntegerField()
    text = models.CharField(max_length=2048)
    image = models.ImageField(null=True, blank=True, upload_to='questions/')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Question'
        verbose_name_plural = 'Questions'


class Choice(models.Model):
    question = models.ForeignKey(Question, related_name='choices', on_delete=models.CASCADE)
    text = models.CharField(max_length=1024)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = 'Choice'
        verbose_name_plural = 'Choices'


class Result(BaseModel):
    class STATE(models.IntegerChoices):
        NEW = 0, "New"
        FINISHED = 1, "Finished"

    user = models.ForeignKey(get_user_model(), related_name='results', on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, related_name='results', on_delete=models.CASCADE)
    state = models.PositiveSmallIntegerField(default=STATE.NEW, choices=STATE.choices)
    uuid = models.UUIDField(default=uuid4, db_index=True, unique=True)
    current_order_number = models.PositiveSmallIntegerField(default=0)
    num_correct_answers = models.PositiveSmallIntegerField(default=0)
    num_incorrect_answers = models.PositiveSmallIntegerField(default=0)

    class Meta:
        verbose_name = 'Result'
        verbose_name_plural = 'Results'

    def update_result(self, order_number, question, selected_choices):
        correct_choice = [choice.is_correct for choice in question.choices.all()]
        correct_answer = True
        for k in zip(selected_choices, correct_choice):
            correct_answer &= (k[0] == k[1])

        self.num_correct_answers += int(correct_answer)
        self.num_incorrect_answers += 1 - int(correct_answer)
        self.current_order_number = order_number

        if order_number == question.exam.questions.count():
            self.state = self.STATE.FINISHED

        self.save()

    def points(self):
        return max(0, self.num_correct_answers - self.num_incorrect_answers)

    def time(self):
        return self.update_timestamp.replace(microsecond=0) - self.create_timestamp.replace(microsecond=0)

quiz/forms.py
from django import forms
from django.core.exceptions import ValidationError

from quiz.models import Choice


class QuestionInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        if not (self.instance.QUESTION_MIN_LIMIT <= len(self.forms) <= self.instance.QUESTION_MAX_LIMIT):
            raise ValidationError(
                f'Количество вопросов должно быть в диапазоне '
                f'от {self.instance.QUESTION_MIN_LIMIT} '
                f'до {self.instance.QUESTION_MAX_LIMIT}'
            )

        order_num_start = 1
        for form in self.forms:
            if form.instance.order_num == order_num_start:
                order_num_start += 1
            else:
                raise ValidationError('Неправильный порядок вопросов')

        for form in self.forms:
            if form.instance.order_num > self.instance.QUESTION_MAX_LIMIT:
                raise ValidationError(f'Максимально возможный порядковый номер: {self.instance.QUESTION_MAX_LIMIT}')


class ChoiceInlineFormSet(forms.BaseInlineFormSet):
    def clean(self):
        num_correct_answers = sum(form.cleaned_data['is_correct'] for form in self.forms)

        if num_correct_answers == 0:
            raise ValidationError('Необходимо выбрать как минимум 1 вариант.')

        if num_correct_answers == len(self.forms):
            raise ValidationError('НЕ разрешено выбирать все варианты')


class ChoiceForm(forms.ModelForm):
    is_selected = forms.BooleanField(required=False)

    class Meta:
        model = Choice
        fields = ['text']


ChoicesFormSet = forms.modelformset_factory(
    model=Choice,
    form=ChoiceForm,
    extra=0
)

quiz/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic.list import MultipleObjectMixin

from quiz.forms import ChoicesFormSet
from quiz.models import Exam
from quiz.models import Question
from quiz.models import Result


class ExamListView(ListView):
    model = Exam
    template_name = 'exams/list.html'
    context_object_name = 'exams'


class ExamDetailView(LoginRequiredMixin, DetailView, MultipleObjectMixin):
    model = Exam
    template_name = 'exams/details.html'
    context_object_name = 'exam'
    pk_url_kwarg = 'uuid'
    paginate_by = 3

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('uuid')
        return self.model.objects.get(uuid=uuid)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(object_list=self.get_queryset(), **kwargs)
        return context

    def get_queryset(self):
        return Result.objects.filter(
            exam=self.get_object(),
            user=self.request.user
        ).order_by('state', '-create_timestamp')


class ExamResultCreateView(LoginRequiredMixin, CreateView):
    def post(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        result = Result.objects.create(
            user=request.user,
            exam=Exam.objects.get(uuid=uuid),
            state=Result.STATE.NEW,
            current_order_number=0
        )

        result.save()

        return HttpResponseRedirect(
            reverse(
                'quiz:question',
                kwargs={
                    'uuid': uuid,
                    'res_uuid': result.uuid,
                }
            )
        )


class ExamResultQuestionView(LoginRequiredMixin, UpdateView):
    def get(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        result = Result.objects.get(uuid=kwargs.get('res_uuid'))
        question = Question.objects.get(
            exam__uuid=uuid,
            order_num=result.current_order_number + 1
        )

        choices = ChoicesFormSet(queryset=question.choices.all())

        return render(request, 'exams/question.html', context={'question': question, 'choices': choices})

    def post(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        res_uuid = kwargs.get('res_uuid')
        result = Result.objects.get(uuid=res_uuid)
        question = Question.objects.get(
            exam__uuid=uuid,
            order_num=result.current_order_number + 1
        )
        choices = ChoicesFormSet(data=request.POST)
        selected_choices = ['is_selected' in form.changed_data for form in choices.forms]
        if sum(selected_choices) == 1:
            result.update_result(result.current_order_number + 1, question, selected_choices)
        else:
            raise ValueError('Выберите ОДИН вариант ответа ;)')

        if result.state == Result.STATE.FINISHED:
            return HttpResponseRedirect(
                reverse(
                    'quiz:result_details',
                    kwargs={
                        'uuid': uuid,
                        'res_uuid': result.uuid
                    }
                )
            )

        return HttpResponseRedirect(
            reverse(
                'quiz:question',
                kwargs={
                    'uuid': uuid,
                    'res_uuid': res_uuid,
                }
            )
        )


class ExamResultDetailView(LoginRequiredMixin, DetailView):
    model = Result
    template_name = 'results/details.html'
    context_object_name = 'result'
    pk_url_kwarg = 'uuid'

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('res_uuid')

        return self.get_queryset().get(uuid=uuid)


class ExamResultUpdateView(LoginRequiredMixin, UpdateView):
    def get(self, request, *args, **kwargs):
        uuid = kwargs.get('uuid')
        res_uuid = kwargs.get('res_uuid')
        user = request.user

        result = Result.objects.get(
            user=user,
            uuid=res_uuid,
            exam__uuid=uuid,
        )

        return HttpResponseRedirect(
            reverse(
                'quiz:question',
                kwargs={
                    'uuid': uuid,
                    'res_uuid': result.uuid,
                }
            )
        )


class ExamResultDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = ['accounts.view_statistics']
    model = Result
    pk_url_kwarg = 'uuid'
    template_name = 'results/delete.html'
    context_object_name = 'result'

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('res_uuid')

        return self.get_queryset().get(uuid=uuid)

    def get_success_url(self):
        return reverse('quiz:details', kwargs={'uuid': self.object.exam.uuid})

quiz/templates/exams/details.html
{% extends 'base.html' %}

{% block title %}
    Описание теста
{% endblock %}

{% block header %}
    Тест: {{ exam.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td>Описание</td>
                            <td>{{ exam.description }}</td>
                        </tr>
                        <tr>
                            <td>Кол-во вопросов</td>
                            <td>{{ exam.questions_count }}</td>
                        </tr>
                        <tr>
                            <td>Кол-во запусков</td>
                            <td>{{ exam.results.count }}</td>
                        </tr>
                        <tr>
                            <td>Лучший результат</td>
                            <td>N/A</td>
                        </tr>
                        <tr>
                            <td>Кто получил лучший результат</td>
                            <td>N/A</td>
                        </tr>
                        <tr>
                            <td>Последний запуск</td>
                            <td>N/A</td>
                        </tr>
                    </tbody>
              </table>
            </div>
        </div>
        <div class="row">
            <form method="post"
                  class="d-flex justify-content-center mt-5 mb-2"
                  action="{% url 'quiz:result_create' exam.uuid %}">
                {% csrf_token %}
                <input class="btn btn-success m-3" type="submit" value="START">
                <a class="btn btn-primary m-3" href="{% url 'quiz:list' %}">Вернуться к списку тестов</a>
            </form>
        </div>
        {% if object_list %}
            <table class="table table-striped table-hover">
                <tr>
                    <th></th>
                    <th>Дата старта</th>
                    <th>Баллы</th>
                    <th>Статус</th>
                    <th>Время</th>
                    <th>Действие</th>
                </tr>
                {% for result in object_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ result.create_timestamp|date:'d-m-Y H:i' }}</td>
                    <td>{{ result.points }}</td>
                    <td>{{ result.get_state_display }}</td>
                    <td>{{ result.time }}</td>
                    <td>
                        {% if result.state == result.STATE.NEW %}
                            <a class="btn btn-warning" href="{% url 'quiz:result_update' exam.uuid result.uuid %}">
                                Продолжить
                            </a>
                            <a class="btn btn-danger" href="{% url 'quiz:result_delete' exam.uuid result.uuid %}">
                                Удалить
                            </a>
                        {% else %}
                            <a class="btn btn-success" href="{% url 'quiz:result_details' exam.uuid result.uuid %}">
                                Посмотреть
                            </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% if is_paginated %}
                <div class="p-1 m-1">
                    {% include 'includes/pagination.html' %}
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

quiz/templates/exams/list.html
{% extends 'base.html' %}

{% block title %}
    Список тестов
{% endblock %}

{% block header %}
    Список тестов.
{% endblock %}

{% block content %}
    {% if exams %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th></th>
                    <th>Название</th>
                    <th>Описание</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for exam in exams %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ exam.title }}</td>
                    <td>{{ exam.description }}</td>
                    <td><a href="{% url 'quiz:details' uuid=exam.uuid %}">Подробнее</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Тестов ещё нет здесь!</p>
    {% endif %}
{% endblock %}

quiz/templates/exams/question.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block title %}
    Описание теста
{% endblock %}

{% block header %}
{#    {{ question.order_num|negative }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ question.text }}#}
    {{ question.order_num }}.&nbsp;{{ question.text }}
{# (question.order_num - 1) * 100 // question.exam.questions_count    #}
{#    {% with question.order_num|add:-1|multi:100|dived:question.exam.questions_count as progress_level %}#}
    {% expression '(%1 - 1) * 100 // %2' question.order_num question.exam.questions_count as progress_level %}
    <div class="progress">
      <div class="progress-bar"
           role="progressbar"
           style="width: {{ progress_level }}%"
           aria-valuenow="{{ progress_level }}"
           aria-valuemin="0"
           aria-valuemax="100">
      </div>
    </div>
{#    {% endwith %}#}
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" autocomplete="off">
            {% csrf_token %}
            {{ choices.management_form }}
            {% for form in choices %}
                <div class="mt-1">
                    {{ form.is_selected }} <label for="{{ form.is_selected.id_for_label }}">
                        {{ form.text.value }}
                    </label>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success mt-5">Дальше ></button>
        </form>
    </div>
{% endblock %}